### ISSUE TITLE
Build for OpenERP docker container failure

### ISSUE THREAD

**Issue by bharatak** [Bhamni/bahmni-docker#4]
Looks like there is a recent change in centos:7 repo and a conflict in python versions being used.  The docker build is failing.

Try running - docker build -t bahmni/erp build/openerp

and it returns a failure.  This needs to be fixed

**Comment by mihirk** [comment]
@bharatak Centos 6 was on Python 2.6 an upgrade to Centos7 means Python 2.7 that is a lot of changes. Specially in all the pip packages as well as OpenERP.

**Comment by bharatak** [comment]
@mihirk I didn't anticipate it would be a lot of changes.  We can start with centos:6.6 base container and try fixing it.

**Comment by bharatak** [comment]
Used tinyerp/ubuntu-openerp as the base image and configured it to work with bahmni addons.
