### ISSUE TITLE
Bahmni Installation

### ISSUE THREAD

**Issue by deepakrv** [Bhamni/bahmni-docker#8]
Hello
My name is deepak and i am currently trying to set up my Bahmni software for test and developer purposes.
So for now i just want to set up Bahmni in order to use and implement it.
I have installed centOS FRESH 6.4 and using the following link,
"[Install+Bahmni+on+CentOS](https://bahmni.atlassian.net/wiki/display/BAH/Install+Bahmni+on+CentOS)"<<(Link).

**DURING THE INSTALLATION I'M FACING THE FOLLOWING ERRORS**

1.

Installed:
postgresql92-server.x86_64 0:9.2.16-1PGDG.rhel6

Dependency Installed:
postgresql92.x86_64 0:9.2.16-1PGDG.rhel6
postgresql92-libs.x86_64 0:9.2.16-1PGDG.rhel6

Complete!
Initializing database: [ OK ]
Starting postgresql-9.2 service: [ OK ]
--2016-05-11 09:44:29-- ##https://github.com/Bahmni/emr-functional-tests/blob/master/dbdump/pgsql_backup.sql.gz?raw=true
Resolving github.com... 192.30.252.121
Connecting to github.com|192.30.252.121|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: ##https://github.com/Bahmni/emr-functional-tests/raw/master/dbdump/pgsql_backup.sql.gz [following]
--2016-05-11 09:44:30-- ##https://github.com/Bahmni/emr-functional-tests/raw/master/dbdump/pgsql_backup.sql.gz
Connecting to github.com|192.30.252.121|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: ##https://raw.githubusercontent.com/Bahmni/emr-functional-tests/master/dbdump/pgsql_backup.sql.gz [following]
--2016-05-11 09:44:31-- ##https://raw.githubusercontent.com/Bahmni/emr-functional-tests/master/dbdump/pgsql_backup.sql.gz
Resolving raw.githubusercontent.com... 103.245.222.133
Connecting to raw.githubusercontent.com|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35093933 (33M) [application/octet-stream]
Saving to: “pgsql_backup.sql.gz”

100%[======================================>] 35,093,933 328K/s in 35s

2016-05-11 09:45:09 (973 KB/s) - “pgsql_backup.sql.gz” saved [35093933/35093933]

NOTICE: database "CAMBIAR_CLAVE" does not exist, skipping
NOTICE: database "DEMO" does not exist, skipping
NOTICE: database "arsh" does not exist, skipping
NOTICE: database "bahmnireportsdata" does not exist, skipping
NOTICE: database "clinlims" does not exist, skipping
NOTICE: database "ghanshyam" does not exist, skipping
NOTICE: database "jklo" does not exist, skipping
NOTICE: database "lab" does not exist, skipping
NOTICE: database "mydb" does not exist, skipping
NOTICE: database "nueva" does not exist, skipping
NOTICE: database "openerp" does not exist, skipping
NOTICE: database "openerp1" does not exist, skipping
NOTICE: database "pacsdb" does not exist, skipping
NOTICE: database "referenceData" does not exist, skipping
NOTICE: database "reference_data" does not exist, skipping
NOTICE: database "test" does not exist, skipping
NOTICE: database "test2" does not exist, skipping
NOTICE: database "test_replication_db" does not exist, skipping
NOTICE: database "testdb" does not exist, skipping
NOTICE: database "testkl" does not exist, skipping
NOTICE: database "zsh" does not exist, skipping
NOTICE: database "zsh1" does not exist, skipping
ERROR: role "postgres" already exists

Question : I have not priorly installed any postgress database instances. I ignored this error and passed by it. Can i install and link to the postgresql database for openErp later? Is this only related to the backup test data provided?

2.

Out of 62 packages of Bahmni , the openers one always failed to download properly which leads to an error installing it.

openerp-7.0-20130301-002301/openerp/report/print_xml.py
openerp-7.0-20130301-002301/openerp/pooler.py
openerp-7.0-20130301-002301/openerp/exceptions.py
openerp-7.0-20130301-002301/PKG-INFO
openerp-7.0-20130301-002301/README
openerp-7.0-20130301-002301/setup.py
openerp-7.0-20130301-002301/setup.cfg
openerp-7.0-20130301-002301/setup_rpm.sh
warning: no directories found matching 'tests'
warning: no files found matching 'gunicorn.conf.py'
warning: no previously-included files matching '_pyc' found anywhere in distribution
warning: no previously-included files matching '_~' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
openerp.addons.web.tests.qunitsuite.suite: module references file
openerp.addons.resource.faces.utils: module references file

openerp.modules.module: module references file
could not identify current directory: No such file or directory
could not identify current directory: No such file or directory
error reading information on service openerp: No such file or directory
Installing : bahmni-web-0.80-373.noarch 67/72
groupadd: group 'bahmni' already exists
useradd: user 'bahmni' already exists
useradd: user 'bahmni' already exists
Running bahmni_config migrations
- . /etc/bahmni-web/bahmni-web.conf
  ++ OPENMRS_DB_SERVER=localhost

Liquibase Update Failed: Communications link failure

Question : How do i fix this?

3.

Installing : bahmni-lab-0.80-58.noarch 68/72
groupadd: group 'bahmni' already exists
useradd: user 'bahmni' already exists
The database clinlims already exits
Adding required extensions
psql:scripts/setupExtensions.sql:1: ERROR: could not open extension control file "/usr/pgsql-9.2/share/extension/uuid-ossp.control": No such file or directory
- . /etc/bahmni-lab/bahmni-lab.conf
  ++ export SERVER_PORT=8081
  ++ SERVER_PORT=8081
  ++ export BASE_DIR=/var/run/bahmni-lab

This is another error that i come across.

**Kindly help me resolve this issues.
Thanking you all.**
And lets talk more about this, so we learn more to make it easier to install Bahmni and other open source softs.. in future..

**Comment by gsluthra** [comment]
Please use OpenMRS Talk for discussions, and not github. Here is the link for reference: 
https://talk.openmrs.org/t/error-messages-during-installation-of-v0-81-bahmni/6249
